export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
export const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
export const SUPABASE_WAITLIST_SIGNUPS_TABLE_NAME = import.meta.env
	.VITE_SUPABASE_WAITLIST_SIGNUPS_TABLE_NAME;
